import React, {useEffect,useId,useMemo,useState} from 'react';
import {ageOnDate,dateLabel,formatHeight,playerHash,playerPoints as points,resolvePlayerSeason,searchPlayers} from './player-view.js';
import './players.css';

function Portrait({player,large=false}) {
  const [failed,setFailed]=useState(false);
  const image=player.entityType==='team_defense'?player.logo:player.headshot;
  useEffect(()=>setFailed(false),[image]);
  return <span className={large?'player-headshot-wrap':'player-search-portrait'}>{image&&!failed?<img src={image} alt={large?`${player.name} ${player.entityType==='team_defense'?'logo':'headshot'}`:''} loading={large?'eager':'lazy'} onError={()=>setFailed(true)}/>:<span className="player-image-fallback" aria-label="Image unavailable">{player.entityType==='team_defense'?'D/ST':player.name?.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>}</span>;
}
export function PlayerSearch({players,compact=false}) {
  const [query,setQuery]=useState(''),[position,setPosition]=useState(''),[type,setType]=useState('player'),[limit,setLimit]=useState(24);
  const inputId=useId();
  const matches=useMemo(()=>searchPlayers(players,query,{position,type:compact?'':type}),[players,query,position,type,compact]);
  useEffect(()=>setLimit(24),[query,position,type]);
  const visible=compact&&!query.trim()?[]:matches.slice(0,compact?8:limit);
  return <div className={`player-search ${compact?'player-search-compact':''}`}>
    <label htmlFor={inputId}>{compact?'Search for another player':'Find a player'}</label>
    <input id={inputId} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Pocky Football players…" autoComplete="off"/>
    {!compact&&<div className="player-filters"><label className="select-control">Entity<select aria-label="Player entity" value={type} onChange={e=>{setType(e.target.value);setPosition('');}}><option value="player">Players</option><option value="team_defense">Team defenses</option></select></label>{type==='player'&&<label className="select-control">Position<select aria-label="Player position" value={position} onChange={e=>setPosition(e.target.value)}><option value="">All positions</option>{['QB','RB','WR','TE','K'].map(p=><option key={p}>{p}</option>)}</select></label>}<span aria-live="polite">{matches.length} {type==='player'?'players':'defenses'} · A–Z</span></div>}
    {(!compact||query.trim())&&<div className="player-search-results" aria-label="Player search results">
      {visible.map(player=><a key={player.espnId} className="player-search-result" href={playerHash(player.espnId)} onClick={()=>setQuery('')}><Portrait player={player}/><span><strong>{player.name}</strong><small>{player.position} · Latest NFL team {player.nflTeam||'—'}</small></span></a>)}
      {!matches.length&&<p className="player-empty" role="status">No Pocky Football players found.</p>}
    </div>}
    {!compact&&matches.length>limit&&<button className="player-more" onClick={()=>setLimit(limit+24)}>Show more players</button>}
  </div>;
}
function BioItem({label,value,featured=false}) {return value!=null&&value!==''?<div className={featured?'bio-item bio-featured':'bio-item'}><dt>{label}</dt><dd>{value}</dd></div>:null;}
function Profile({player}) {
  const defense=player.entityType==='team_defense';
  const draft=player.nflDraft;
  const draftText=draft?.year?[draft.year,draft.round?`Round ${draft.round}`:null,draft.overallPick?`Pick ${draft.overallPick}`:null,draft.team].filter(Boolean).join(' · '):null;
  return <section className="player-profile"><Portrait player={player} large/><div className="player-profile-main"><p className="page-eyebrow">Pocky Football {defense?'Team Defense':'Player'}</p><h2>{player.name}</h2><p className="player-nfl-line">{player.position}{!defense&&player.jerseyNumber!=null?` · #${player.jerseyNumber}`:''}</p><dl className="player-bio"><BioItem label="Latest NFL team" value={player.nflTeam}/>{!defense&&<><BioItem label="Age" value={ageOnDate(player.birthDate)} featured/><BioItem label="Height" value={formatHeight(player.heightInches)}/><BioItem label="Weight" value={player.weightPounds?`${player.weightPounds} lb`:null}/><BioItem label="Born" value={dateLabel(player.birthDate)}/><BioItem label="College" value={player.college}/><BioItem label="NFL Draft" value={draftText}/><BioItem label="Rookie season" value={player.rookieSeason}/></>}</dl><p className="player-note">{defense?'NFL team defense; no individual biography.':'Profile reflects the latest metadata snapshot. Team and jersey may differ in earlier seasons.'}</p></div></section>;
}
function Stats({stats}) {return <dl className="team-overview player-stats">{[['League-scored FPTS',points(stats.points)],['Scored weeks',stats.weeks],['FPTS / scored week',points(stats.average)],['Highest week',stats.high?`${points(stats.high.points)} · ${stats.high.season} W${stats.high.week}`:'—'],['Fantasy starts',stats.starts],['Starter FPTS',points(stats.starterPoints)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}
function PlayerTable({caption,headers,children}) {return <div className="content-card table-card"><div className="player-table-scroll"><table className="player-table"><caption className="sr-only">{caption}</caption><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div>;}
const eventLabels={free_agent_add:'Free agent add',waiver_add:'Waiver add',drop:'Drop',trade:'Trade'};
function TeamList({teams,Team}) {return teams.length?<div className="player-team-list">{teams.map(t=><Team key={t.teamId} team={t}/>)}</div>:<span>—</span>;}
export function PlayerDetail({detail,requestedSeason,onSeasonChange,Section,Team}) {
  const [tab,setTab]=useState('career');
  const selection=resolvePlayerSeason(detail.seasons,requestedSeason);
  const seasons=selection==='All-Time'?detail.seasons:detail.seasons.filter(s=>String(s.season)===selection);
  const weeks=seasons.flatMap(s=>s.weeks).sort((a,b)=>b.season-a.season||b.week-a.week);
  const transactions=seasons.flatMap(s=>s.transactions.map(t=>({...t,season:s.season}))).sort((a,b)=>(b.timestamp||'').localeCompare(a.timestamp||''));
  const stats=selection==='All-Time'?detail.career:seasons[0].summary;
  return <><Profile player={detail.profile}/><div className="player-season-row"><label className="select-control">Season<select aria-label="Player season" value={selection} onChange={e=>onSeasonChange(e.target.value)}><option>All-Time</option>{detail.seasons.map(s=><option key={s.season}>{s.season}</option>)}</select></label></div>
    <nav className="player-tabs" role="tablist" aria-label="Player sections">{[['career','Career'],['weekly','Weekly Log'],['transactions','Transactions'],['draft','Draft']].map(([id,label])=><button key={id} id={`player-tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`player-panel-${id}`} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    <div role="tabpanel" id={`player-panel-${tab}`} aria-labelledby={`player-tab-${tab}`}>
    {tab==='career'&&<><Section title="Pocky Football Career" meta={selection}><p className="player-note">League-scored totals use available actual scores in finalized fantasy weeks, including explicit zero scores. Scored weeks are not NFL games played. Starter points count only finalized weeks in active fantasy slots; missing scores stay unknown.</p><div className="content-card"><Stats stats={stats}/></div></Section>
      <Section title="Season History"><PlayerTable caption="Player season totals" headers={['Season','Fantasy teams observed','Scored weeks','FPTS','FPTS / week','Starts','Starter FPTS']}>{seasons.map(s=><tr key={s.season}><th scope="row">{s.season}{!s.complete&&<small>In progress</small>}</th><td><TeamList teams={s.ownership.map(o=>o.team)} Team={Team}/></td><td>{s.summary.weeks}</td><td className="player-fpts">{points(s.summary.points)}</td><td>{points(s.summary.average)}</td><td>{s.summary.starts}</td><td>{points(s.summary.starterPoints)}</td></tr>)}</PlayerTable></Section>
      <Section title="Fantasy Team History" meta="Recorded evidence"><p className="player-note">Weekly snapshots and recorded movements establish these appearances; no continuous ownership periods are inferred.</p>{seasons.map(s=><details className="player-history content-card" key={s.season} open={seasons.length===1}><summary>{s.season} · {s.ownership.length} fantasy {s.ownership.length===1?'team':'teams'}</summary><p className="player-note">{s.rosterSnapshotLabel}: {s.rosterSnapshot.length?s.rosterSnapshot.map(t=>t.name).join(', '):'Not on a recorded roster snapshot'}</p>{s.ownership.map(o=><div className="player-owner-row" key={o.team.teamId}><Team team={o.team}/><span>{o.weeks.length?`Roster weeks: ${o.weeks.join(', ')}`:'No weekly roster snapshot'}<small>{o.evidence.map(e=>({draft:'Draft selection',transaction:'Recorded transaction',weekly_roster:'Weekly roster',current_roster:'Current roster',final_roster:'Final roster'})[e]).join(' · ')}</small></span></div>)}</details>)}</Section></>}
    {tab==='weekly'&&<><Section title="Recent Weeks" meta="Latest 5 represented weeks"><WeekLog weeks={weeks.slice(0,5)} Team={Team}/></Section><Section title="Complete Weekly Log" meta={selection}><p className="player-note">A blank fantasy team means no weekly ownership snapshot is available. Bench and IR points are shown but are not starter contributions. Live points are provisional and excluded from totals.</p><WeekLog weeks={weeks} Team={Team}/></Section></>}
    {tab==='draft'&&<Section title="Fantasy Draft History" meta="Authoritative selections"><PlayerTable caption="Fantasy draft selections" headers={['Season','Fantasy team','Round','Pick in round','Overall pick']}>{seasons.flatMap(s=>s.draft.map((d,i)=><tr key={`${s.season}-${i}`}><th scope="row">{s.season}</th><td><Team team={d.team}/></td><td>{d.round??'—'}</td><td>{d.pickInRound??'—'}</td><td>#{d.overallPick??'—'}</td></tr>))}</PlayerTable>{!seasons.some(s=>s.draft.length)&&<p className="player-empty">No fantasy draft selections recorded.</p>}</Section>}
    {tab==='transactions'&&<Section title="Pocky Football Transactions" meta="Most recent first"><p className="player-note">Executed movements from the audited activity feed. Fantasy draft selections appear in Draft. Times follow the source’s processed or proposed timestamp.</p>{seasons.map(s=><details className="player-history content-card" key={s.season}><summary>{s.season} activity coverage · {s.activityCoverage.status.replaceAll('_',' ')}</summary><p className="player-note">{s.activityCoverage.limitation||'Historical details are limited to the available audited feed.'}</p></details>)}<ol className="player-transactions">{transactions.map((t,i)=><li key={`${t.season}-${i}`}><div><time dateTime={t.timestamp||undefined}>{dateLabel(t.timestamp)||'Date unavailable'}</time><small>{t.season} · Week {t.week??'—'}</small></div><strong>{eventLabels[t.type]||t.type.replaceAll('_',' ')}</strong><div className="player-transfer">{t.fromTeams.length>0&&<TeamList teams={t.fromTeams} Team={Team}/>}<span>{t.type==='drop'?'→ Released':t.fromTeams.length?'→':'→ Acquired by'}</span>{t.toTeams.length>0&&<TeamList teams={t.toTeams} Team={Team}/>}</div></li>)}</ol>{!transactions.length&&<p className="player-empty">No executed acquisitions, drops, or trades recorded.</p>}</Section>}
    </div></>;
}
function WeekLog({weeks,Team}) {return weeks.length?<PlayerTable caption="Weekly league fantasy performances" headers={['Season / Week','NFL matchup','Fantasy roster / slot','FPTS','Status']}>{weeks.map(w=><tr key={`${w.season}-${w.week}`}><th scope="row">{w.season} · W{w.week}</th><td>{w.nflTeam||'—'}{w.nflOpponent?` vs. ${w.nflOpponent}`:''}</td><td>{w.rosters.length?w.rosters.map(r=><div key={r.team.teamId}><Team team={r.team}/><small>{r.slot} · {points(r.points)} FPTS</small></div>):'Not observed'}</td><td className="player-fpts">{points(w.points)}</td><td>{w.status==='final'?'Final':w.status==='live'?'Live':'Upcoming'}</td></tr>)}</PlayerTable>:<p className="player-empty">No weekly scores available.</p>;}
export default function PlayersPage({path,loadData,playerId,requestedSeason='All-Time',onSeasonChange,Section,Team}) {
  const [index,setIndex]=useState(null),[detail,setDetail]=useState(null),[error,setError]=useState(null);
  useEffect(()=>{let live=true;setIndex(null);setError(null);loadData(path).then(d=>{if(live)setIndex(d);}).catch(()=>{if(live)setError('Player search is unavailable.');});return()=>{live=false;};},[path,loadData]);
  useEffect(()=>{let live=true;setDetail(null);setError(null);if(!index||playerId==null)return;
    const entry=index.players.find(p=>p.espnId===playerId);
    if(!entry){setError('Player not found in Pocky Football history.');return;}
    loadData(entry.path).then(d=>{if(live)setDetail(d);}).catch(()=>{if(live)setError('Player history is unavailable.');});return()=>{live=false;};},[index,playerId,loadData]);
  return <div className="players-page">{playerId!=null&&<a className="player-back" href="#/players">← All players</a>}{index&&<PlayerSearch players={index.players} compact={playerId!=null}/>} {error?<p role="alert">{error}</p>:!index||playerId!=null&&!detail?<p role="status">Loading players…</p>:detail&&playerId!=null?<PlayerDetail key={playerId} detail={detail} requestedSeason={requestedSeason} onSeasonChange={onSeasonChange} Section={Section} Team={Team}/>:null}</div>;
}
